//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AXCH
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialValues
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialValues()
        {
            this.MaterialValuesAccounting = new HashSet<MaterialValuesAccounting>();
        }
    
        public int Code_MV { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public string Category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialValuesAccounting> MaterialValuesAccounting { get; set; }
    }
}
