//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AXCH
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialValuesAccounting
    {
        public int Code_MV_Ac { get; set; }
        public string InventoryCardNum { get; set; }
        public System.DateTime ComplDate { get; set; }
        public int Code_MV_FK { get; set; }
        public string InventoryNum { get; set; }
        public System.DateTime CommisioningDate { get; set; }
        public Nullable<decimal> InitalCost { get; set; }
        public int ServiceNumber_FK { get; set; }
        public Nullable<int> UsefulLife { get; set; }
        public string InvoiceNumberDate { get; set; }
        public Nullable<int> Amount { get; set; }
        public string EquipmentType { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Length { get; set; }
        public string SerialNumber { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual MaterialValues MaterialValues { get; set; }
    }
}
